# Generated by Django 3.2.9 on 2021-11-25 11:48

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(db_column='course', max_length=250)),
                ('subject', models.CharField(db_column='subject', max_length=250)),
                ('exam_title', models.CharField(db_column='exam_title', max_length=250)),
                ('date_of_exam', models.CharField(db_column='date_of_exam', max_length=250)),
                ('start_time', models.CharField(db_column='start_time', max_length=250)),
                ('end_time', models.CharField(db_column='end_time', max_length=250)),
                ('status', models.CharField(default='INSERT', max_length=20)),
            ],
            options={
                'db_table': 'ExamDetail',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=250)),
                ('course', models.CharField(db_column='course', max_length=250)),
                ('date_of_birth', models.DateField(blank=True, db_column='date_of_birth', null=True)),
                ('email', models.CharField(db_column='email', max_length=250)),
                ('mobile', models.CharField(db_column='mobile', max_length=250)),
                ('username', models.CharField(db_column='username', max_length=250)),
                ('password', models.CharField(db_column='password', max_length=250)),
            ],
            options={
                'db_table': 'StudentDetails',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_status', models.IntegerField(db_column='form_status', default=0)),
                ('form_id', models.ForeignKey(db_column='form_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Exam_form', to='exam.examdetail')),
                ('student_id', models.ForeignKey(db_column='student_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ExamSession', to='exam.studentdetails')),
            ],
            options={
                'db_table': 'ExamSession',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExamAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_marks', models.CharField(db_column='max_marks', max_length=250, null=True)),
                ('element_id', models.IntegerField(db_column='Element_Id')),
                ('attribute', jsonfield.fields.JSONField()),
                ('form_id', models.ForeignKey(db_column='form_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ExamAttributes_id', to='exam.examdetail')),
            ],
            options={
                'db_table': 'ExamAttribute',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_attribute', jsonfield.fields.JSONField()),
                ('ans_id', models.ForeignKey(db_column='ans_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ExamSession_id', to='exam.examsession')),
                ('ques_id', models.ForeignKey(db_column='Ques_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Element_que_Id', to='exam.examattribute')),
            ],
            options={
                'db_table': 'ExamAnswer',
                'managed': True,
            },
        ),
    ]
