# Generated by Django 3.2.9 on 2021-11-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examdetail',
            name='date_of_exam',
            field=models.CharField(db_column='date_of_exam', max_length=250),
        ),
    ]
